shelldivers/Just1RCe

- docs/Architecture/Client.md
Client 객체에 대한 문서 업데이트
DBContext 관련 내용 추가
어떤 변경 사항이 있나요?
> docs(Client) : update document about Client

- includes/context_holder.h
- srcs/context_holder/context_holder.cc
DbContext를 handling하는 객체, single ton하게 구현하였습니다.
> feat : implement contextholder

- includes/dbcontext.h
- add virtual pure method PartClientFromChannelByNames to the DbContext
Resolves: #59 
어떤 변경 사항이 있나요?
> feat(DbContext) : add method

- docs/Architecture/Commands.md
서버와 클라이언트에서 보내는 명령어와 응답 형식을 정리했습니다
서버와 클라이언트간에 주고받는 규칙인 Numeric을 정리했습니다
> #50 docs commands 정리

- includes/numeric.h
- srcs/parse/parser.cc
> #62 [CHORE] NUMERIC 의 CMD_SUCCESS -> IRC_NOERROR 로 변경

- docs/Architecture/Commands.md
구현할 명령어들을 Markdown으로 정리
정리한 내용을 토대로 command handler를 구현한다
> #70 docs: add commands doc

- includes/command_handler.h
커맨드를 handling 하는 함수는 std::map 등을 활용하여 command의 이름과 매칭한다. 
따라서 커맨드의 이름(std::string)과 실제 동작을 위한 handling 함수를 매핑하기 위해서는 std::map등이 필요하며,
하나의 std::map에 서로 다른 핸들링 함수를 매핑하기 위해서는 polymorphism이 필요한데, 이를 상속을 바탕으로 구현한다.
여러 command(nick, join, part, ...)를 수행하는 command handler를 함수 객체로 정의하고, 이들이 CommandHandler를 상속받도록 구현한다.
command mapping은 대략 다음과 같다.
``` c++
std::map<std::string, Just1RCe::CommandHandler *> command_map;
```
어떤 변경 사항이 있나요?
> 23 feat command handler interface

- includes/client.h
- srcs/client/client_network_info.cc
해당 클라이언트를 향하는 소켓의 fd를 반환하는 GetFd() 추가
InMemoryDbContext에서 fd와 client의 nick name을 mapping하기 위해서 client의 fd를 얻어야 하고, 이를 위해서 해당 메서드를 추가함.
어떤 변경 사항이 있나요?
> feat(Client) : add method

- includes/dbcontext.h
- nick_name들을 client_nick_name으로 일괄 변경
- mode table 관련 매개변수 순서 변경
가독성 증짐 및 여러 함수의 시그니처가 일관성을 갖도록 하기 위함
> chore(DbContext) : rename elements

- includes/channel.h
- srcs/channel/channel_invite_list.cc
한 채널에 사용자가 join하기 위해서 초대를 받아야 가능한 경우가 있음.
해당 채널에 초대받은 인원인지 식별하기 위해서 해당 기능을 추가함.
어떤 변경 사항이 있나요?
> feat : add invite list to the channel

- includes/client.h
- srcs/client/Client_auth.cc
- srcs/client/client.cc
- 해당 사용자의 PASS 통과 여부 관련한 메서드 추가
- 해당 사용자가 PASS USER NICK의 세 커맨드를 모두 통과했는지 확인하는 메서드 추가
irc 프로토콜에서 인증된 사용자를 식별하기 위해서 관련 메서드 추가
어떤 변경 사항이 있나요?
> feat(Client) : implement client authentication

- includes/dbcontext.h
- includes/in_memory_db_context.h
- srcs/in_memory_db_context/client_table.cc
- member var std::map<std::string, int> nick_name_to_fd_table_
- member function virtual void SetNickNameToFd(std::string const &client_nick_name,
int const fd);
virtual int GetFdByNickName(std::string const &client_nick_name); virtual void DeleteNickNameToFd(std::string const &client_nick_name);
클라이언트의 nick_name 필드를 가지고 client를 검색할 필요가 생겼으므로, 이를 위한 자료구조와 메서드를 제공함.
> #90 feat : implement nick name to fd mapping

- includes/command_mapping.h
- srcs/command_mapping/command_mapping.cc
명령어들을 처리하는 command handler들을 command에 맞게 map에 저장하는 초기화 함수 구현
PASS 명령어를 처리하는 PassCommandHandler의 경우에는 생성자 인자로 password를 받아 저장한다
> #93 feat: command mapping register 구현

- CMakeLists.txt
빌드할 구현파일들을 모두 CMakeList에 추가하였습니다
> #108 ci: 빌드할 구현파일 추가

- includes/command_mapping.h
- includes/commands/nick_command_handler.h
- includes/commands/pass_command_handler.h
- includes/commands/user_command_handler.h
- includes/config.h
- includes/parser.h
- includes/response_generator.h
- includes/service.h
- srcs/channel/channel.cc
- srcs/commands/nick_command_handler.cc
- srcs/commands/pass_command_handler.cc
- srcs/commands/user_command_handler.cc
- srcs/in_memory_db_context/mapping_table.cc
- srcs/parse/parser.cc
- srcs/responser/response_generator.cc
- srcs/service/event_handler.cc
- srcs/service/run_irc_server.cc
빌드에 성공하기 위하여 문법적 에러를 해결하였습니다.
어떤 변경 사항이 있나요?
> 113 bug debug

- includes/channel.h
- srcs/channel/channel.cc
- srcs/in_memory_db_context/mapping_table.cc
채널에 소속된 사용자의 수를 관리하는 size_t 변수 및 channel 삭제 메커니즘 추가
어떤 변경 사항이 있나요?
> 119 feat 사용자 이탈part과 연동하여 channel 삭제

- includes/service.h
- srcs/commands/nick_command_handler.cc
- srcs/service/event_handler.cc
- srcs/service/run_irc_server.cc
기존 구현에서는 unknown command, 혹은 구현되지 않은 command에 대한 입력을 상정하지 않았기에 segfault를 받아왔음. 
이를 해결하기 위하여 관련 경우를 처리하기 위한 분기를 추가함.
어떤 변경 사항이 있나요?
> 123 bug service routine unknown command handling

- includes/commands/part_command_handler.h
- srcs/commands/part_command_handler.cc
PART 명령어를 구현하였습니다
주어진 3가지 Numeric을 처리하였습니다
- ERR_NEEDMOREPARAMS (461)
- ERR_NOTONCHANNEL (442)
- ERR_NOSUCHCHANNEL (403)
> #128 feat: PART 명령어 구현 완료

- includes/commands/kick_command_handler.h
- srcs/commands/kick_command_handler.cc
사용자를 채널로부터 퇴장시키는 명령어를 구현하였습니다.
> #131 feat: KICK 명령어 구현 완료

- includes/commands/invite_command_handler.h
- srcs/commands/invite_command_handler.cc
> #130 feat: INVITE 명령어 구현완료

- includes/commands/mode_command_handler.h
- srcs/commands/mode_command_handler.cc
- srcs/commands/modes/mode_i.cc
- srcs/commands/modes/mode_k.cc
- srcs/commands/modes/mode_l.cc
- srcs/commands/modes/mode_o.cc
- srcs/commands/modes/mode_t.cc
MODE 커맨드를 처리하는 command handler 구현
어떤 변경 사항이 있나요?
> #125 feat mode 명령어 구현

- includes/commands/privmsg_command_handler.h
- srcs/commands/privmsg_command_handler.cc
#PRIVMSG 명령어 구현 완료 \#132
메시지를 전송하는 명령어를 구현하였습니다
들어온 매개변수가 채널이면 채널 사용자 모두에게 메시지를 보낸다
들어온 매개변수가 클라이언트면 해당 클라이언트에게만 메시지를 보낸다
> #132 feat: PRIVMSG 명령어 구현 완료

- includes/client_mode.h
- includes/commands/mode_command_handler.h
- srcs/client/client_mode.cc
- srcs/command_mapping/command_mapping.cc
- srcs/commands/mode_command_handler.cc
구현한 command를 통합하고, 등록하여 사용 가능한 상태로 준비한다.
어떤 변경 사항이 있나요?
> #147 feat command 구현 통합

- srcs/commands/join_command_handler.cc
- srcs/commands/mode_command_handler.cc
- 처음으로 채널에 JOIN하는 사용자가 channel의 operator로 선정되도록 설정
- 채널이 아닌 사용자를 대상으로 하는 MODE 커맨드를 무시하도록 설정 
어떤 변경 사항이 있나요?
> #150 bug mode 명령어 오류

- srcs/commands/join_command_handler.cc
- srcs/commands/part_command_handler.cc
식별된 에러 수정.
- 1. 채널에서 특정 인원이 part했을 때, 그 외의 채널 소속 인원에게 누가 channel에서 이탈했는지 통지
- 2. join에서 채널에 대하여 초대 여부를 검사할 때, user-host mask로 초대 여부 식별하기
어떤 변경 사항이 있나요?
> #156 #155 bug wrong part message

- srcs/commands/nick_command_handler.cc
- srcs/commands/quit_command_handler.cc
Numeric 응답이 아닌 일반적인 사용자 응답에 대한 양식 변경
- [nickname] --> [nickname]![username]@[hostname] 으로 변경
> #146 fix: 기본 Response 의 양식 변경

- srcs/commands/join_command_handler.cc
- srcs/in_memory_db_context/client_table.cc
현재 서버에서는 한 번 초대되면, 초대 여부가 사라지지 않음. 따라서 해당 사용자가 서버를 떠날 때 초대된 기록이 있는 채널이 있다면, 이를 지워줘야 함.
어떤 변경 사항이 있나요?
> #145 client 삭제 시 bug invite list 정리

- srcs/in_memory_db_context/client_table.cc
전방 선언 부재로 인한 build 실패
어떤 변경 사항이 있나요?
> fix: add front declaration
